# This is a basic workflow that is manually triggered

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Send greeting
      run: echo Hello world
      
    - name: multiline script
      run:  |
        echo Add other actions to build,
        echo test and deploy your project.
